### ISSUE TITLE
Close button content overlap

### ISSUE THREAD

**Issue by Romick2005** [alexbrazier/react-native-network-logger#20]
Hi, excellent job!

Just one small UI thing noticed: 
Close button is overlap with request url. 
I think having close button in same header row as more would be better. 

![image](https://user-images.githubusercontent.com/17779660/90135024-b293ca00-dd7a-11ea-8f55-fcb7c9643ce2.png)

**Comment by alexbrazier** [comment]
Hi @Romick2005, thanks for opening the issue and sorry for the slow response/fix. I've implemented a fix in #23 that increases the padding on the details page so that the close button no longer overlaps.

I've also just opened a new PR (#24) that allows you to use your existing back button within your app and gets rid of the custom close button completely.
