### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by ryanvanderpol** [alexbrazier/react-native-network-logger#7]
When tapping on a specific request in the list view I am unable to view the details. I receive the following error message:

```
Error: Text strings must be rendered within a <Text> component.
```

This is in a fairly new app using RN `0.62.2`

Looking at the code in `Header.tsx` it seems it's rendering `children` into a `<Text>` element. Not exactly sure what's in `children` but that seems to be where the error occurs.

**Screenshots**
![Screen Shot 2020-06-24 at 12 04 11 PM](https://user-images.githubusercontent.com/1936460/85591002-e6703000-b612-11ea-80f9-a66398766865.png)

**Platform:**
- [x] iOS
- [x] Android

**Comment by alexbrazier** [comment]
Hi @ryanvanderpol, thanks for reporting the issue. I think it was caused by a failing request returning an empty string causing an empty string to be rendered outside a `Text` component.

It should now be fixed in version `1.3.1`. If there is still an issue the feel free to reopen or create another.
