### ISSUE TITLE
Does not work with Pinch

### ISSUE THREAD

**Issue by chathuralakmal** [alexbrazier/react-native-network-logger#72]
**Describe the bug**
Network Calls made by Pinch not showing the log.

**Platform:**
- [x ] iOS
- [x ] Android

**Comment by alexbrazier** [comment]
I assume you are referring to this library? https://github.com/localz/react-native-pinch

`react-native-network-logger` relies on [XHRInterceptor](https://github.com/facebook/react-native/blob/main/Libraries/Network/XHRInterceptor.js) from react-native, which I think can only intercept network requests made on the JS side. Looking at `react-native-pinch` it uses a native module to make the request which is why it isn't being intercepted.

I'm open to suggestions for how to fix it, but sounds like we might need to write some native code to intercept the native requests as well that then hook into this library.
