### ISSUE TITLE
The response body is in the `Loading...` state

### ISSUE THREAD

**Issue by FDiskas** [alexbrazier/react-native-network-logger#73]
**Describe the bug**
The response body is in the `Loading...` state

**Expected behavior**
I should see the body response

**Screenshots**
![image](https://user-images.githubusercontent.com/468006/224060325-7f778915-392a-4068-8ffb-997e44bbcb5b.png)

**Platform:**
- [x] iOS
- [ ] Android (not tested)

**Additional context**
react-native-network-logger: v1.14.0
react-native: v0.71.3

was working on the previous react-native version v0.69.5

**Comment by FDiskas** [comment]
But the good news is that if we click to share - we have a body

**Comment by alexbrazier** [comment]
Hi @FDiskas, thanks for raising this issue. I've just upgraded react-native on the example app and I'm now getting the same issue. I'll try to take a look into this shortly to see what has changed and get a fix out.

**Comment by alexbrazier** [comment]
Should be fixed and released in `1.14.1`.

https://github.com/alexbrazier/react-native-network-logger/releases/tag/v1.14.1

**Comment by FDiskas** [comment]
By updating to the latest `1.14.1` I get white screen with only search input
![image](https://user-images.githubusercontent.com/468006/225903277-b148a4c8-7f63-4bc9-8172-8c6e1378ad1c.png)

**Comment by alexbrazier** [comment]
Were you using `1.14.0` before? The only thing that changed was how the request and response body renders on ios so I wouldn't expect it to affect the main screen. I also updated some dev/build deps which may have changed the build output but wouldn't expect to see that screen if it was broken.

Have you called `startNetworkLogging` https://github.com/alexbrazier/react-native-network-logger#start-logging somewhere in the app? Otherwise it will only enable it after you open the logger for the first time.

**Comment by FDiskas** [comment]
Looks like the core issue is disabled Hermes. So the problem is not on your end.
